# ----------------------------------------------------
# Config generated by Search::CreateConfigFile()
# @author Mikhail Starovoyt
# @version 4.5.2
# ----------------------------------------------------

# ----------------------------------------------------
# Top Section
# ----------------------------------------------------
{$sTopSection}
# ----------------------------------------------------



# Источник данных для поиска
source catalog
{ldelim}
    # Тип данных
    # Доступные типы: mysql, pgsql, mssql, xmlpipe, xmlpipe2, odbc
    type                        = mysql

    # Необходимые параметры для подключения к базе данных
    sql_host            = localhost
    sql_user            = zsite
    sql_pass            = 654940
    sql_db              = zsite
    sql_port            = 3306  # опциональный, по умолчанию 3306

    # пред-запрос, выполняется перед выполнением основного запроса на получение данных из базы
    # В нашей базе данные хранятся в UTF-8, чтобы поиск по русским символам работал успешно выполним соответсвующий запрос
    sql_query_pre               = SET NAMES utf8

    # запрос, который получает данные документов для поиска
    # первым полем обязательно должен идти уникальный положительный ID документа
    sql_query           = SELECT * FROM zs_search


    # поля, по которым может идти группировка, фильтрация и сортировка
#    sql_attr_uint    = sku
#    sql_attr_uint    = product_id
#    sql_attr_uint    = model



    # document info query, ONLY for CLI search (ie. testing and debugging)
    # optional, default is empty
    # must contain $id macro and must fetch the document by that id
    sql_query_info              = SELECT * FROM zs_search WHERE price != 0 AND product_id=$id
{rdelim}

# индекс каталога товаров для поиска
index catalog
{ldelim}
    enable_star = 1
    # Источник данных для индексирования
    source            = catalog

    # Адрес, где будут хранится данные индекса
    path            = /var/data/catalog/

     # Индекс с учетом морфологии
     morphology        = stem_enru
     # Минимальная длина слова для индексации
     min_word_len        = 3
     min_infix_len       = 3
     # Кодировка
     charset_type        = utf-8

#     min_prefix_len = 2
     prefix_fields = sku

{rdelim}

indexer
{ldelim}
        mem_limit                               = 512M
{rdelim}


searchd
{ldelim}
        port                                    = 9312
        log                                             = /var/log/searchd.log
        query_log                               = /var/log/query.log
        read_timeout                    = 5
        max_children                    = 30
        pid_file                                = /var/log/searchd.pid
        max_matches                             = 1000
        seamless_rotate                 = 1
        preopen_indexes                 = 0
        unlink_old                              = 1
        compat_sphinxql_magics = 0 # the future is now

{rdelim}